# Generated by Django 5.1.5 on 2025-01-18 17:33

import blog.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=75, null=True)),
                ('metatitle', models.CharField(blank=True, db_column='metaTitle', max_length=100, null=True)),
                ('slug', models.CharField(max_length=100)),
                ('context', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=50, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('text', models.TextField(blank=True, null=True)),
                ('createdat', models.DateField(db_column='createdAt')),
                ('url', models.URLField(blank=True, null=True)),
                ('github_url', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=75, null=True)),
                ('metatitle', models.CharField(blank=True, db_column='metaTitle', max_length=100, null=True)),
                ('pid', models.CharField(default=blog.models.generate_short_uuid, max_length=30, unique=True)),
                ('summary', models.TextField(blank=True, null=True)),
                ('createdat', models.DateField(db_column='createdAt')),
                ('updatedat', models.DateField(db_column='updatedAt')),
                ('publishedat', models.DateField(db_column='publishedAt')),
                ('content', models.TextField(blank=True, null=True)),
                ('category', models.ManyToManyField(related_name='post_category', to='blog.category')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=75, null=True)),
                ('metatitle', models.CharField(blank=True, db_column='metaTitle', max_length=100, null=True)),
                ('slug', models.CharField(max_length=100)),
                ('content', models.TextField(blank=True, null=True)),
                ('post', models.ManyToManyField(related_name='post_tag', to='blog.post')),
            ],
        ),
    ]
