# Generated by Django 5.1.5 on 2025-01-18 17:34

import blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='pid',
            field=models.CharField(default=blog.models.generate_short_uuid, max_length=30),
        ),
    ]
