# Generated by Django 5.1.5 on 2025-01-18 17:35

import blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_project_pid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='pid',
            field=models.CharField(default=blog.models.generate_short_uuid, max_length=30, unique=True),
        ),
    ]
