# Generated by Django 5.1.5 on 2025-01-18 10:26

import blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_remove_project_images_alter_project_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='slug',
        ),
        migrations.AddField(
            model_name='post',
            name='pid',
            field=models.CharField(default=blog.models.generate_short_uuid, max_length=30, unique=True),
        ),
    ]
